dist: xenial
sudo: false
language: python
matrix:
  include:
  - python: "2.7"
  - python: "3.7"
install: pip install -r requirements.txt pycodestyle websocket-client
before_script:
  - mv CONFIG_SAMPLE.py CONFIG.py
script:
  - pycodestyle --max-line-length=120 cloud_tools lambda_function *.py
  - ./cloud_tools -h
notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - peter@pakos.uk
